### Create Ad (change POST address to vercel after hosting so i can check it then too with that button) / use the .env var

POST http://localhost:3000/api/ads/[id]
Content-Type: application/json
Cookie: next-auth.session-token={{$dotenv COOKIE}}

{
  "title": "Test Ad",
  "price": 25.0,
  "category": "books",
  "description": "Lightly used book",
  "contact": "test@example.com",
  "imageUrl": "https://example.com/image.jpg",
  "userEmail": "test@example.com"
}